### ISSUE TITLE
Can it extend device relations?

### ISSUE THREAD

**Issue by ilyatm** [zenoss/zenpacklib#106]
I want to extend Device class relations, without adding new device class to ZenPack.

**Comment by dougsyer** [comment]
i got it working almost extending an existing class except the api / gui layer wouldnt registerd.  

When I tried to extend a subclass of device.device, i got the relations working by adding them into the __init__ file which basically import and adds a patch to zenoss.  then i added the relations into the new component in zenpacklib.  the relations all worked, the javascript and api layer got generated, but it wouldnt register the js/api layer with zenpacklib.  i stopped there since im working on another project  I may have to extend device.device but i hate doing that on principal since I dont want to add a component to 1000's of device if only one device class needs them.

if you want to add the relation to device.device I think you can do that by:

class_relationships:
  - Products.ZenModel.Device.Device 1:MC NewComponentType

**Comment by ilyatm** [comment]
thanks, i have already got it working

**Comment by ilyatm** [comment]
and one more question, can i extend my own class? For example
classes:
  myclass:
    base: [zenpacklib.Component]
  extendedclass:
    base: [myclass]
I can't get to work it.

**Comment by dougsyer** [comment]
thats working for me for example:

RegisteredComponent:
    base: [zenpacklib.HardwareComponent]

    properties:
      description:
        label: Description
        label_width: 200

# Registered Components(RIS Components)
  Gatekeeper:
    base: [RegisteredComponent]
    label: Gatekeeper

I had some strange issues(it may have been me i dont know) when i tried to assign relations at a parent class and have the children inherit them.  I cant remember now if it was a gui problem or a problem with setting non containing classes but I think it was a gui thing.  I gave up on that..  but i have been able to set properties on parent classes and have them inherit.

**Comment by eedgar** [comment]
I think this issue is closed as I have seen people mention they have it working.  Please open a new issue if this is incorrect.
