### ISSUE TITLE
documentation issue on RRDtypes

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#125]
I was able to use COUNTER...assuming this is a documentation error?

rrdtype
    Description:	Type of datapoint. Must be GAUGE or DERIVE.
    Required:	No
    Type:	string (must be either GAUGE or DERIVE)
    Default Value:	GAUGE

**Comment by cluther** [comment]
It's an intentional documentation error. I didn't want to totally disallow COUNTER, but I didn't want to advertise it since DERIVE with rrdmin 0 is a better idea.

**Comment by dougsyer** [comment]
interesting why is derive with min 0 better because it explicitly protects against negative values?

**Comment by cluther** [comment]
@dougsyer: There's no functional difference between DERIVE_MIN_0 and COUNTER in Zenoss 5. However, there is a functional difference in Zenoss 4 because it controls the RRDtool type.

RRDtool has some extra-clever logic on the COUNTER type that attempts to account for cases where counters reset or roll over. It uses this logic to provide a delta value at the collection interval immediately following the reset or roll. It sounds great, but it's frequently wrong and results in a large positive or negative spike in your graph when it's wrong.

DERIVE with its minimum set to 0 is a lot simpler to understand. No value is recorded if the delta is negative. So in most cases of counter reset or roll you just don't get a value for the next collection interval.

I much prefer missing a sample in this case than storing completely wrong data.

**Comment by dougsyer** [comment]
Woah that explains ia few things!!

**Comment by dougsyer** [comment]
Wrong on wraps? Or wrong on calculations?

**Comment by cluther** [comment]
It has the potential to store the wrong value on the first collection following a reset or wrap of the counter.
