### ISSUE TITLE
zenpack lib relations mapping for non containing relations

### ISSUE THREAD

**Issue by sulakshm** [zenoss/zenpacklib#58]
Let me start by stating that zenpacklib rocks!!
I was able to accomplish linking container relations and get them in the UI way easily.
We specify relations in the yaml spec. I can see that the parent relation 'name' is easily identified through label. But what is the corresponding relation from the child?
For ex, [COMP1]++-[COMP2]
In the above, if COMP1 'label' is 'Comp1', then the relation is 'comp1s'. (small first letter and plural)
But what is the equivalent from Comp2 to get to Comp1?

Secondly, I am trying to model non containing relations between components.
Say, 
[ROOT]++-[Comp1] /* This is good containing relation, parent child relations*/
[ROOT]++-[Comp2] /* This is good containing relation, parent child relations */
[Comp1]*-.-*[Comp2]. /* HOW?? To many non containing relations between components */

Now, how can I establish the relation between them? Any references please.

Thanks, your pointers are much appreciated.

**Comment by sulakshm** [comment]
I tried creating the above relation using zenpacklib in this git.

I found below issues which are likely bugs?

They create both components as ToManyContRelationship within it.
Additionally, I see there exists get_relname() and set_relname() helper functions in each Comp1 and Comp2. But using get_relname() fails because the attribute is not found. 
This is because, the attribute is named after the label in small letter, followed by plural convention.
The get_function though is looking for an attribute by component name.

Can you please let me know whether non-containing relations like above successfully model with zenpacklib?

**Comment by cluther** [comment]
Non-containing 1:M and 1:1 relationships can be modeled with zenpacklib. Let me use a simple manager, host and VM model to demonstrate. The idea being that Manager is the device type and it has relationships containing Host and VM component types. Each Host as a ToMany non-containing relationship to VM called "vms" and each VM has a corresponding ToOne non-containing relationship to host.

```
// Containing relationships.
[Manager]++-[Host]
[Manager]++-[VM]
// Non-containing relationships.
[Host]1-.-*[VM]
```

This will create the following relationships. Note that a plural name is used for all ToMany* relationships and a singular name is used for all ToOne relationships.

* Manager.hosts (ToManyCont)
* Manager.vms (ToManyCont)
* Host.manager (ToOne)
* Host.vms (ToMany)
* VM.manager (ToOne)
* VM.host (ToOne)

In addition to creating these relationships, the following methods will be created to assist in the modeling of the non-containing relationships.

* Host.set_vms(VM_ids_list)
* VM.set_host(host_id_string)

So in your modeler plugin you have the option of adding a "set_vms" property to your Host ObjectMaps, a "set_host" property to your VM ObjectMaps, or both. If you choose to only set this relationship from one side, be sure that the RelationshipMap for that side is returned last from your modeler plugin's process method. You must do this because the object on the other side of the relationship must be created before a relationship to it can be created.

**Comment by sulakshm** [comment]
Hi Chester,
Thanks for the details. It really helps.

But you did not mention M:N ToMany to ToMany non-containing relations.
[Comp1]*-.-*[Comp2].
Is this not supported?

LN

**Comment by cluther** [comment]
Yes, many-to-many relationships are also supported. They must be non-containing, and the `[Comp1]*-.-*[Comp2]` syntax you used is correct.

The following relationships would be created.

* Comp1.comp2s (ToMany)
* Comp2.comp1s (ToMany)

The following methods would be created to aid in populating the relationships.

* Comp1.set_comp2s(comp2_ids_list)
* Comp2.set_comp1s(comp1_ids_list)
